// Do not touch this file. It is generated by Zerve-Sync
// To update the file, modify the zerve field in package.json.zerve and run "npx zerve-sync"

import * as zStoreData from './data-sync.json';
import * as zStoreSchema from './schema-sync.json';
import { createZStoreClient } from '@zerve/client/StoreClient';

const zStoreProtocol = "https://";
const zStoreOrigin = "alpha.zerve.app";
const zStorePath = ".z/store/ev/demo";

export interface QuestionAnswer {
  Question?: null;
  Response?: null;
}

export type HumanText = {
  text: string;
  bold?: boolean;
  italic?: boolean;
  strike?: boolean;
  underline?: boolean;
  code?: boolean;
  linkHref?: string;
}[];

export type BannerFileSchema = string;

export type HeadlineFileSchema = HumanText;

export const zClient = createZStoreClient(
  zStoreProtocol,
  zStoreOrigin,
  zStorePath,
  zStoreSchema,
  zStoreData
);

export const zAccessors = {
  Banner: zClient.createAccessor<BannerFileSchema>("Banner"),
  Headline: zClient.createAccessor<HeadlineFileSchema>("Headline"),
}

export const useBanner = zAccessors.Banner.use;
export const useHeadline = zAccessors.Headline.use;

